# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'arayuz.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1215, 799)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 110, 731, 531))
        self.groupBox.setObjectName("groupBox")
        self.lblVid = QtWidgets.QLabel(self.groupBox)
        self.lblVid.setGeometry(QtCore.QRect(0, 0, 721, 531))
        self.lblVid.setObjectName("lblVid")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(730, 110, 451, 531))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 30, 451, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkMesafe = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkMesafe.setObjectName("checkMesafe")
        self.verticalLayout.addWidget(self.checkMesafe)
        self.checkMaske = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkMaske.setObjectName("checkMaske")
        self.verticalLayout.addWidget(self.checkMaske)
        self.checkGirisCikis = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkGirisCikis.setObjectName("checkGirisCikis")
        self.verticalLayout.addWidget(self.checkGirisCikis)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 190, 451, 81))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnPlaka = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.btnPlaka.setObjectName("btnPlaka")
        self.horizontalLayout_2.addWidget(self.btnPlaka)
        self.btnSil = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.btnSil.setObjectName("btnSil")
        self.horizontalLayout_2.addWidget(self.btnSil)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 731, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnBaslat = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnBaslat.setObjectName("btnBaslat")
        self.horizontalLayout.addWidget(self.btnBaslat)
        self.btnGoruntuKaydet = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnGoruntuKaydet.setObjectName("btnGoruntuKaydet")
        self.horizontalLayout.addWidget(self.btnGoruntuKaydet)
        self.btnKapat = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnKapat.setObjectName("btnKapat")
        self.horizontalLayout.addWidget(self.btnKapat)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1215, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "GÖRÜNTÜ"))
        self.lblVid.setText(_translate("MainWindow", "TextLabel"))
        self.groupBox_2.setTitle(_translate("MainWindow", "AYARLAMALAR"))
        self.checkMesafe.setText(_translate("MainWindow", "MESAFE(PX*CM)"))
        self.checkMaske.setText(_translate("MainWindow", "MASKE ANALİZ"))
        self.checkGirisCikis.setText(_translate("MainWindow", "GİRİŞ ÇIKIŞ"))
        self.btnPlaka.setText(_translate("MainWindow", "Plaka Analiz"))
        self.btnSil.setText(_translate("MainWindow", "PushButton"))
        self.btnBaslat.setText(_translate("MainWindow", "BAŞLAT"))
        self.btnGoruntuKaydet.setText(_translate("MainWindow", "GORUNTU KAYDET"))
        self.btnKapat.setText(_translate("MainWindow", "KAPAT"))


